- filename: file_brain_AXT2_207_2070586
  path: multicoil_train/file_brain_AXT2_207_2070586.h5
  slice: null
- filename: file_brain_AXT2_207_2070021
  path: multicoil_val/file_brain_AXT2_207_2070021.h5
  slice: null
- filename: file_brain_AXT2_207_2070003
  path: multicoil_train/file_brain_AXT2_207_2070003.h5
  slice: null
- filename: file_brain_AXT2_208_2080485
  path: multicoil_train/file_brain_AXT2_208_2080485.h5
  slice: null
- filename: file_brain_AXT2_202_2020376
  path: multicoil_train/file_brain_AXT2_202_2020376.h5
  slice: null
- filename: file_brain_AXT2_202_2020512
  path: multicoil_train/file_brain_AXT2_202_2020512.h5
  slice: null
- filename: file_brain_AXT2_209_6001400
  path: multicoil_train/file_brain_AXT2_209_6001400.h5
  slice: null
- filename: file_brain_AXT2_210_6001651
  path: multicoil_train/file_brain_AXT2_210_6001651.h5
  slice: null
- filename: file_brain_AXT2_205_2050086
  path: multicoil_train/file_brain_AXT2_205_2050086.h5
  slice: null
- filename: file_brain_AXT2_200_2000044
  path: multicoil_train/file_brain_AXT2_200_2000044.h5
  slice: null
- filename: file_brain_AXT2_201_2010067
  path: multicoil_train/file_brain_AXT2_201_2010067.h5
  slice: null
- filename: file_brain_AXT2_201_2010209
  path: multicoil_val/file_brain_AXT2_201_2010209.h5
  slice: null
- filename: file_brain_AXT2_210_6001883
  path: multicoil_train/file_brain_AXT2_210_6001883.h5
  slice: null
- filename: file_brain_AXT2_200_6002551
  path: multicoil_train/file_brain_AXT2_200_6002551.h5
  slice: null
