- filename: file_brain_AXT2_200_2000290
  path: multicoil_train/file_brain_AXT2_200_2000290.h5
  predefined_mask: null
  slice: 0
- filename: file_brain_AXT2_200_2000290
  path: multicoil_train/file_brain_AXT2_200_2000290.h5
  predefined_mask: null
  slice: 1
- filename: file_brain_AXT2_200_2000290
  path: multicoil_train/file_brain_AXT2_200_2000290.h5
  predefined_mask: null
  slice: 2
- filename: file_brain_AXT2_200_2000290
  path: multicoil_train/file_brain_AXT2_200_2000290.h5
  predefined_mask: null
  slice: 3
- filename: file_brain_AXT2_202_2020365
  path: multicoil_train/file_brain_AXT2_202_2020365.h5
  predefined_mask: null
  slice: 0
- filename: file_brain_AXT2_202_2020365
  path: multicoil_train/file_brain_AXT2_202_2020365.h5
  predefined_mask: null
  slice: 1
- filename: file_brain_AXT2_202_2020365
  path: multicoil_train/file_brain_AXT2_202_2020365.h5
  predefined_mask: null
  slice: 2
- filename: file_brain_AXT2_202_2020365
  path: multicoil_train/file_brain_AXT2_202_2020365.h5
  predefined_mask: null
  slice: 3
- filename: file_brain_AXT2_202_2020365
  path: multicoil_train/file_brain_AXT2_202_2020365.h5
  predefined_mask: null
  slice: 4
- filename: file_brain_AXT2_202_2020365
  path: multicoil_train/file_brain_AXT2_202_2020365.h5
  predefined_mask: null
  slice: 5
- filename: file_brain_AXT2_202_2020365
  path: multicoil_train/file_brain_AXT2_202_2020365.h5
  predefined_mask: null
  slice: 6
- filename: file_brain_AXT2_202_2020365
  path: multicoil_train/file_brain_AXT2_202_2020365.h5
  predefined_mask: null
  slice: 7
- filename: file_brain_AXT2_202_2020365
  path: multicoil_train/file_brain_AXT2_202_2020365.h5
  predefined_mask: null
  slice: 8
- filename: file_brain_AXT2_202_2020365
  path: multicoil_train/file_brain_AXT2_202_2020365.h5
  predefined_mask: null
  slice: 9
- filename: file_brain_AXT2_202_2020365
  path: multicoil_train/file_brain_AXT2_202_2020365.h5
  predefined_mask: null
  slice: 10
- filename: file_brain_AXT2_202_2020365
  path: multicoil_train/file_brain_AXT2_202_2020365.h5
  predefined_mask: null
  slice: 11
- filename: file_brain_AXT2_202_2020365
  path: multicoil_train/file_brain_AXT2_202_2020365.h5
  predefined_mask: null
  slice: 12
- filename: file_brain_AXT2_202_2020365
  path: multicoil_train/file_brain_AXT2_202_2020365.h5
  predefined_mask: null
  slice: 13
- filename: file_brain_AXT2_202_2020365
  path: multicoil_train/file_brain_AXT2_202_2020365.h5
  predefined_mask: null
  slice: 14
- filename: file_brain_AXT2_202_2020365
  path: multicoil_train/file_brain_AXT2_202_2020365.h5
  predefined_mask: null
  slice: 15
- filename: file_brain_AXT2_203_2030198
  path: multicoil_train/file_brain_AXT2_203_2030198.h5
  predefined_mask: null
  slice: 0
- filename: file_brain_AXT2_203_2030198
  path: multicoil_train/file_brain_AXT2_203_2030198.h5
  predefined_mask: null
  slice: 1
- filename: file_brain_AXT2_203_2030198
  path: multicoil_train/file_brain_AXT2_203_2030198.h5
  predefined_mask: null
  slice: 2
- filename: file_brain_AXT2_203_2030198
  path: multicoil_train/file_brain_AXT2_203_2030198.h5
  predefined_mask: null
  slice: 3
- filename: file_brain_AXT2_203_2030198
  path: multicoil_train/file_brain_AXT2_203_2030198.h5
  predefined_mask: null
  slice: 4
- filename: file_brain_AXT2_203_2030198
  path: multicoil_train/file_brain_AXT2_203_2030198.h5
  predefined_mask: null
  slice: 5
- filename: file_brain_AXT2_203_2030198
  path: multicoil_train/file_brain_AXT2_203_2030198.h5
  predefined_mask: null
  slice: 6
- filename: file_brain_AXT2_203_2030198
  path: multicoil_train/file_brain_AXT2_203_2030198.h5
  predefined_mask: null
  slice: 7
- filename: file_brain_AXT2_203_2030198
  path: multicoil_train/file_brain_AXT2_203_2030198.h5
  predefined_mask: null
  slice: 8
- filename: file_brain_AXT2_203_2030198
  path: multicoil_train/file_brain_AXT2_203_2030198.h5
  predefined_mask: null
  slice: 9
- filename: file_brain_AXT2_203_2030198
  path: multicoil_train/file_brain_AXT2_203_2030198.h5
  predefined_mask: null
  slice: 10
- filename: file_brain_AXT2_203_2030198
  path: multicoil_train/file_brain_AXT2_203_2030198.h5
  predefined_mask: null
  slice: 11
- filename: file_brain_AXT2_203_2030198
  path: multicoil_train/file_brain_AXT2_203_2030198.h5
  predefined_mask: null
  slice: 12
- filename: file_brain_AXT2_203_2030198
  path: multicoil_train/file_brain_AXT2_203_2030198.h5
  predefined_mask: null
  slice: 13
- filename: file_brain_AXT2_203_2030198
  path: multicoil_train/file_brain_AXT2_203_2030198.h5
  predefined_mask: null
  slice: 14
- filename: file_brain_AXT2_203_2030198
  path: multicoil_train/file_brain_AXT2_203_2030198.h5
  predefined_mask: null
  slice: 15
- filename: file_brain_AXT2_200_2000057
  path: multicoil_train/file_brain_AXT2_200_2000057.h5
  predefined_mask: null
  slice: 0
- filename: file_brain_AXT2_200_2000057
  path: multicoil_train/file_brain_AXT2_200_2000057.h5
  predefined_mask: null
  slice: 1
- filename: file_brain_AXT2_200_2000057
  path: multicoil_train/file_brain_AXT2_200_2000057.h5
  predefined_mask: null
  slice: 2
- filename: file_brain_AXT2_200_2000057
  path: multicoil_train/file_brain_AXT2_200_2000057.h5
  predefined_mask: null
  slice: 3
- filename: file_brain_AXT2_200_2000057
  path: multicoil_train/file_brain_AXT2_200_2000057.h5
  predefined_mask: null
  slice: 4
- filename: file_brain_AXT2_200_2000057
  path: multicoil_train/file_brain_AXT2_200_2000057.h5
  predefined_mask: null
  slice: 5
- filename: file_brain_AXT2_200_2000057
  path: multicoil_train/file_brain_AXT2_200_2000057.h5
  predefined_mask: null
  slice: 6
- filename: file_brain_AXT2_200_2000057
  path: multicoil_train/file_brain_AXT2_200_2000057.h5
  predefined_mask: null
  slice: 7
- filename: file_brain_AXT2_200_2000057
  path: multicoil_train/file_brain_AXT2_200_2000057.h5
  predefined_mask: null
  slice: 8
- filename: file_brain_AXT2_200_2000057
  path: multicoil_train/file_brain_AXT2_200_2000057.h5
  predefined_mask: null
  slice: 9
- filename: file_brain_AXT2_200_2000057
  path: multicoil_train/file_brain_AXT2_200_2000057.h5
  predefined_mask: null
  slice: 10
- filename: file_brain_AXT2_200_2000057
  path: multicoil_train/file_brain_AXT2_200_2000057.h5
  predefined_mask: null
  slice: 11
- filename: file_brain_AXT2_200_2000057
  path: multicoil_train/file_brain_AXT2_200_2000057.h5
  predefined_mask: null
  slice: 12
- filename: file_brain_AXT2_200_2000057
  path: multicoil_train/file_brain_AXT2_200_2000057.h5
  predefined_mask: null
  slice: 13
- filename: file_brain_AXT2_200_2000057
  path: multicoil_train/file_brain_AXT2_200_2000057.h5
  predefined_mask: null
  slice: 14
- filename: file_brain_AXT2_200_2000057
  path: multicoil_train/file_brain_AXT2_200_2000057.h5
  predefined_mask: null
  slice: 15
- filename: file_brain_AXT2_210_6001778
  path: multicoil_train/file_brain_AXT2_210_6001778.h5
  predefined_mask: null
  slice: 0
- filename: file_brain_AXT2_210_6001778
  path: multicoil_train/file_brain_AXT2_210_6001778.h5
  predefined_mask: null
  slice: 1
- filename: file_brain_AXT2_210_6001778
  path: multicoil_train/file_brain_AXT2_210_6001778.h5
  predefined_mask: null
  slice: 2
- filename: file_brain_AXT2_210_6001778
  path: multicoil_train/file_brain_AXT2_210_6001778.h5
  predefined_mask: null
  slice: 3
- filename: file_brain_AXT2_210_6001778
  path: multicoil_train/file_brain_AXT2_210_6001778.h5
  predefined_mask: null
  slice: 4
- filename: file_brain_AXT2_210_6001778
  path: multicoil_train/file_brain_AXT2_210_6001778.h5
  predefined_mask: null
  slice: 5
- filename: file_brain_AXT2_210_6001778
  path: multicoil_train/file_brain_AXT2_210_6001778.h5
  predefined_mask: null
  slice: 6
- filename: file_brain_AXT2_210_6001778
  path: multicoil_train/file_brain_AXT2_210_6001778.h5
  predefined_mask: null
  slice: 7
- filename: file_brain_AXT2_210_6001778
  path: multicoil_train/file_brain_AXT2_210_6001778.h5
  predefined_mask: null
  slice: 8
- filename: file_brain_AXT2_210_6001778
  path: multicoil_train/file_brain_AXT2_210_6001778.h5
  predefined_mask: null
  slice: 9
- filename: file_brain_AXT2_210_6001778
  path: multicoil_train/file_brain_AXT2_210_6001778.h5
  predefined_mask: null
  slice: 10
- filename: file_brain_AXT2_210_6001778
  path: multicoil_train/file_brain_AXT2_210_6001778.h5
  predefined_mask: null
  slice: 11
- filename: file_brain_AXT2_210_6001778
  path: multicoil_train/file_brain_AXT2_210_6001778.h5
  predefined_mask: null
  slice: 12
- filename: file_brain_AXT2_210_6001778
  path: multicoil_train/file_brain_AXT2_210_6001778.h5
  predefined_mask: null
  slice: 13
- filename: file_brain_AXT2_210_6001778
  path: multicoil_train/file_brain_AXT2_210_6001778.h5
  predefined_mask: null
  slice: 14
- filename: file_brain_AXT2_210_6001778
  path: multicoil_train/file_brain_AXT2_210_6001778.h5
  predefined_mask: null
  slice: 15
- filename: file_brain_AXT2_202_2020491
  path: multicoil_train/file_brain_AXT2_202_2020491.h5
  predefined_mask: null
  slice: 0
- filename: file_brain_AXT2_202_2020491
  path: multicoil_train/file_brain_AXT2_202_2020491.h5
  predefined_mask: null
  slice: 1
- filename: file_brain_AXT2_202_2020491
  path: multicoil_train/file_brain_AXT2_202_2020491.h5
  predefined_mask: null
  slice: 2
- filename: file_brain_AXT2_202_2020491
  path: multicoil_train/file_brain_AXT2_202_2020491.h5
  predefined_mask: null
  slice: 3
- filename: file_brain_AXT2_202_2020491
  path: multicoil_train/file_brain_AXT2_202_2020491.h5
  predefined_mask: null
  slice: 4
- filename: file_brain_AXT2_202_2020491
  path: multicoil_train/file_brain_AXT2_202_2020491.h5
  predefined_mask: null
  slice: 5
- filename: file_brain_AXT2_202_2020491
  path: multicoil_train/file_brain_AXT2_202_2020491.h5
  predefined_mask: null
  slice: 6
