- filename: file_brain_AXT2_202_6000459
  path: multicoil_train/file_brain_AXT2_202_6000459.h5
  predefined_mask: null
  slice: 0
- filename: file_brain_AXT2_202_6000459
  path: multicoil_train/file_brain_AXT2_202_6000459.h5
  predefined_mask: null
  slice: 1
- filename: file_brain_AXT2_202_6000459
  path: multicoil_train/file_brain_AXT2_202_6000459.h5
  predefined_mask: null
  slice: 2
- filename: file_brain_AXT2_202_6000459
  path: multicoil_train/file_brain_AXT2_202_6000459.h5
  predefined_mask: null
  slice: 3
- filename: file_brain_AXT2_202_6000459
  path: multicoil_train/file_brain_AXT2_202_6000459.h5
  predefined_mask: null
  slice: 4
- filename: file_brain_AXT2_202_6000459
  path: multicoil_train/file_brain_AXT2_202_6000459.h5
  predefined_mask: null
  slice: 5
- filename: file_brain_AXT2_202_6000459
  path: multicoil_train/file_brain_AXT2_202_6000459.h5
  predefined_mask: null
  slice: 6
- filename: file_brain_AXT2_202_6000459
  path: multicoil_train/file_brain_AXT2_202_6000459.h5
  predefined_mask: null
  slice: 7
- filename: file_brain_AXT2_202_6000459
  path: multicoil_train/file_brain_AXT2_202_6000459.h5
  predefined_mask: null
  slice: 8
- filename: file_brain_AXT2_202_6000459
  path: multicoil_train/file_brain_AXT2_202_6000459.h5
  predefined_mask: null
  slice: 9
- filename: file_brain_AXT2_202_6000459
  path: multicoil_train/file_brain_AXT2_202_6000459.h5
  predefined_mask: null
  slice: 10
- filename: file_brain_AXT2_202_6000459
  path: multicoil_train/file_brain_AXT2_202_6000459.h5
  predefined_mask: null
  slice: 11
- filename: file_brain_AXT2_202_6000459
  path: multicoil_train/file_brain_AXT2_202_6000459.h5
  predefined_mask: null
  slice: 12
- filename: file_brain_AXT2_202_6000459
  path: multicoil_train/file_brain_AXT2_202_6000459.h5
  predefined_mask: null
  slice: 13
- filename: file_brain_AXT2_202_6000459
  path: multicoil_train/file_brain_AXT2_202_6000459.h5
  predefined_mask: null
  slice: 14
- filename: file_brain_AXT2_202_6000459
  path: multicoil_train/file_brain_AXT2_202_6000459.h5
  predefined_mask: null
  slice: 15
- filename: file_brain_AXT2_201_2010288
  path: multicoil_train/file_brain_AXT2_201_2010288.h5
  predefined_mask: null
  slice: 0
- filename: file_brain_AXT2_201_2010288
  path: multicoil_train/file_brain_AXT2_201_2010288.h5
  predefined_mask: null
  slice: 1
- filename: file_brain_AXT2_201_2010288
  path: multicoil_train/file_brain_AXT2_201_2010288.h5
  predefined_mask: null
  slice: 2
- filename: file_brain_AXT2_201_2010288
  path: multicoil_train/file_brain_AXT2_201_2010288.h5
  predefined_mask: null
  slice: 3
- filename: file_brain_AXT2_201_2010288
  path: multicoil_train/file_brain_AXT2_201_2010288.h5
  predefined_mask: null
  slice: 4
- filename: file_brain_AXT2_201_2010288
  path: multicoil_train/file_brain_AXT2_201_2010288.h5
  predefined_mask: null
  slice: 5
- filename: file_brain_AXT2_201_2010288
  path: multicoil_train/file_brain_AXT2_201_2010288.h5
  predefined_mask: null
  slice: 6
- filename: file_brain_AXT2_201_2010288
  path: multicoil_train/file_brain_AXT2_201_2010288.h5
  predefined_mask: null
  slice: 7
- filename: file_brain_AXT2_201_2010288
  path: multicoil_train/file_brain_AXT2_201_2010288.h5
  predefined_mask: null
  slice: 8
- filename: file_brain_AXT2_201_2010288
  path: multicoil_train/file_brain_AXT2_201_2010288.h5
  predefined_mask: null
  slice: 9
- filename: file_brain_AXT2_201_2010288
  path: multicoil_train/file_brain_AXT2_201_2010288.h5
  predefined_mask: null
  slice: 10
- filename: file_brain_AXT2_201_2010288
  path: multicoil_train/file_brain_AXT2_201_2010288.h5
  predefined_mask: null
  slice: 11
- filename: file_brain_AXT2_201_2010288
  path: multicoil_train/file_brain_AXT2_201_2010288.h5
  predefined_mask: null
  slice: 12
- filename: file_brain_AXT2_201_2010288
  path: multicoil_train/file_brain_AXT2_201_2010288.h5
  predefined_mask: null
  slice: 13
- filename: file_brain_AXT2_200_2000450
  path: multicoil_train/file_brain_AXT2_200_2000450.h5
  predefined_mask: null
  slice: 0
- filename: file_brain_AXT2_200_2000450
  path: multicoil_train/file_brain_AXT2_200_2000450.h5
  predefined_mask: null
  slice: 1
- filename: file_brain_AXT2_200_2000450
  path: multicoil_train/file_brain_AXT2_200_2000450.h5
  predefined_mask: null
  slice: 2
- filename: file_brain_AXT2_200_2000450
  path: multicoil_train/file_brain_AXT2_200_2000450.h5
  predefined_mask: null
  slice: 3
- filename: file_brain_AXT2_200_2000450
  path: multicoil_train/file_brain_AXT2_200_2000450.h5
  predefined_mask: null
  slice: 4
- filename: file_brain_AXT2_200_2000450
  path: multicoil_train/file_brain_AXT2_200_2000450.h5
  predefined_mask: null
  slice: 5
- filename: file_brain_AXT2_200_2000450
  path: multicoil_train/file_brain_AXT2_200_2000450.h5
  predefined_mask: null
  slice: 6
- filename: file_brain_AXT2_200_2000450
  path: multicoil_train/file_brain_AXT2_200_2000450.h5
  predefined_mask: null
  slice: 7
- filename: file_brain_AXT2_200_2000450
  path: multicoil_train/file_brain_AXT2_200_2000450.h5
  predefined_mask: null
  slice: 8
- filename: file_brain_AXT2_200_2000450
  path: multicoil_train/file_brain_AXT2_200_2000450.h5
  predefined_mask: null
  slice: 9
- filename: file_brain_AXT2_200_2000450
  path: multicoil_train/file_brain_AXT2_200_2000450.h5
  predefined_mask: null
  slice: 10
- filename: file_brain_AXT2_200_2000450
  path: multicoil_train/file_brain_AXT2_200_2000450.h5
  predefined_mask: null
  slice: 11
- filename: file_brain_AXT2_200_2000450
  path: multicoil_train/file_brain_AXT2_200_2000450.h5
  predefined_mask: null
  slice: 12
- filename: file_brain_AXT2_200_2000450
  path: multicoil_train/file_brain_AXT2_200_2000450.h5
  predefined_mask: null
  slice: 13
- filename: file_brain_AXT2_200_2000450
  path: multicoil_train/file_brain_AXT2_200_2000450.h5
  predefined_mask: null
  slice: 14
- filename: file_brain_AXT2_200_2000450
  path: multicoil_train/file_brain_AXT2_200_2000450.h5
  predefined_mask: null
  slice: 15
- filename: file_brain_AXT2_208_2080528
  path: multicoil_train/file_brain_AXT2_208_2080528.h5
  predefined_mask: null
  slice: 0
- filename: file_brain_AXT2_208_2080528
  path: multicoil_train/file_brain_AXT2_208_2080528.h5
  predefined_mask: null
  slice: 1
- filename: file_brain_AXT2_208_2080528
  path: multicoil_train/file_brain_AXT2_208_2080528.h5
  predefined_mask: null
  slice: 2
- filename: file_brain_AXT2_208_2080528
  path: multicoil_train/file_brain_AXT2_208_2080528.h5
  predefined_mask: null
  slice: 3
- filename: file_brain_AXT2_208_2080528
  path: multicoil_train/file_brain_AXT2_208_2080528.h5
  predefined_mask: null
  slice: 4
- filename: file_brain_AXT2_208_2080528
  path: multicoil_train/file_brain_AXT2_208_2080528.h5
  predefined_mask: null
  slice: 5
- filename: file_brain_AXT2_208_2080528
  path: multicoil_train/file_brain_AXT2_208_2080528.h5
  predefined_mask: null
  slice: 6
- filename: file_brain_AXT2_208_2080528
  path: multicoil_train/file_brain_AXT2_208_2080528.h5
  predefined_mask: null
  slice: 7
- filename: file_brain_AXT2_208_2080528
  path: multicoil_train/file_brain_AXT2_208_2080528.h5
  predefined_mask: null
  slice: 8
- filename: file_brain_AXT2_208_2080528
  path: multicoil_train/file_brain_AXT2_208_2080528.h5
  predefined_mask: null
  slice: 9
- filename: file_brain_AXT2_208_2080528
  path: multicoil_train/file_brain_AXT2_208_2080528.h5
  predefined_mask: null
  slice: 10
- filename: file_brain_AXT2_208_2080528
  path: multicoil_train/file_brain_AXT2_208_2080528.h5
  predefined_mask: null
  slice: 11
- filename: file_brain_AXT2_208_2080528
  path: multicoil_train/file_brain_AXT2_208_2080528.h5
  predefined_mask: null
  slice: 12
- filename: file_brain_AXT2_208_2080528
  path: multicoil_train/file_brain_AXT2_208_2080528.h5
  predefined_mask: null
  slice: 13
- filename: file_brain_AXT2_208_2080528
  path: multicoil_train/file_brain_AXT2_208_2080528.h5
  predefined_mask: null
  slice: 14
- filename: file_brain_AXT2_208_2080528
  path: multicoil_train/file_brain_AXT2_208_2080528.h5
  predefined_mask: null
  slice: 15
- filename: file_brain_AXT2_207_2070081
  path: multicoil_train/file_brain_AXT2_207_2070081.h5
  predefined_mask: null
  slice: 0
- filename: file_brain_AXT2_207_2070081
  path: multicoil_train/file_brain_AXT2_207_2070081.h5
  predefined_mask: null
  slice: 1
- filename: file_brain_AXT2_207_2070081
  path: multicoil_train/file_brain_AXT2_207_2070081.h5
  predefined_mask: null
  slice: 2
- filename: file_brain_AXT2_207_2070081
  path: multicoil_train/file_brain_AXT2_207_2070081.h5
  predefined_mask: null
  slice: 3
- filename: file_brain_AXT2_207_2070081
  path: multicoil_train/file_brain_AXT2_207_2070081.h5
  predefined_mask: null
  slice: 4
- filename: file_brain_AXT2_207_2070081
  path: multicoil_train/file_brain_AXT2_207_2070081.h5
  predefined_mask: null
  slice: 5
- filename: file_brain_AXT2_207_2070081
  path: multicoil_train/file_brain_AXT2_207_2070081.h5
  predefined_mask: null
  slice: 6
- filename: file_brain_AXT2_207_2070081
  path: multicoil_train/file_brain_AXT2_207_2070081.h5
  predefined_mask: null
  slice: 7
- filename: file_brain_AXT2_207_2070081
  path: multicoil_train/file_brain_AXT2_207_2070081.h5
  predefined_mask: null
  slice: 8
- filename: file_brain_AXT2_207_2070081
  path: multicoil_train/file_brain_AXT2_207_2070081.h5
  predefined_mask: null
  slice: 9
- filename: file_brain_AXT2_207_2070081
  path: multicoil_train/file_brain_AXT2_207_2070081.h5
  predefined_mask: null
  slice: 10
- filename: file_brain_AXT2_207_2070081
  path: multicoil_train/file_brain_AXT2_207_2070081.h5
  predefined_mask: null
  slice: 11
- filename: file_brain_AXT2_207_2070081
  path: multicoil_train/file_brain_AXT2_207_2070081.h5
  predefined_mask: null
  slice: 12
