- filename: file_brain_AXT2_209_2090151
  path: multicoil_train/file_brain_AXT2_209_2090151.h5
  predefined_mask: null
  slice: 0
- filename: file_brain_AXT2_209_2090151
  path: multicoil_train/file_brain_AXT2_209_2090151.h5
  predefined_mask: null
  slice: 1
- filename: file_brain_AXT2_209_2090151
  path: multicoil_train/file_brain_AXT2_209_2090151.h5
  predefined_mask: null
  slice: 2
- filename: file_brain_AXT2_209_2090151
  path: multicoil_train/file_brain_AXT2_209_2090151.h5
  predefined_mask: null
  slice: 3
- filename: file_brain_AXT2_209_2090151
  path: multicoil_train/file_brain_AXT2_209_2090151.h5
  predefined_mask: null
  slice: 4
- filename: file_brain_AXT2_209_2090151
  path: multicoil_train/file_brain_AXT2_209_2090151.h5
  predefined_mask: null
  slice: 5
- filename: file_brain_AXT2_209_2090151
  path: multicoil_train/file_brain_AXT2_209_2090151.h5
  predefined_mask: null
  slice: 6
- filename: file_brain_AXT2_209_2090151
  path: multicoil_train/file_brain_AXT2_209_2090151.h5
  predefined_mask: null
  slice: 7
- filename: file_brain_AXT2_209_2090151
  path: multicoil_train/file_brain_AXT2_209_2090151.h5
  predefined_mask: null
  slice: 8
- filename: file_brain_AXT2_209_2090151
  path: multicoil_train/file_brain_AXT2_209_2090151.h5
  predefined_mask: null
  slice: 9
- filename: file_brain_AXT2_209_2090151
  path: multicoil_train/file_brain_AXT2_209_2090151.h5
  predefined_mask: null
  slice: 10
- filename: file_brain_AXT2_209_2090151
  path: multicoil_train/file_brain_AXT2_209_2090151.h5
  predefined_mask: null
  slice: 11
- filename: file_brain_AXT2_209_2090151
  path: multicoil_train/file_brain_AXT2_209_2090151.h5
  predefined_mask: null
  slice: 12
- filename: file_brain_AXT2_209_2090151
  path: multicoil_train/file_brain_AXT2_209_2090151.h5
  predefined_mask: null
  slice: 13
- filename: file_brain_AXT2_209_2090151
  path: multicoil_train/file_brain_AXT2_209_2090151.h5
  predefined_mask: null
  slice: 14
- filename: file_brain_AXT2_209_2090151
  path: multicoil_train/file_brain_AXT2_209_2090151.h5
  predefined_mask: null
  slice: 15
- filename: file_brain_AXT2_203_2030260
  path: multicoil_train/file_brain_AXT2_203_2030260.h5
  predefined_mask: null
  slice: 0
- filename: file_brain_AXT2_203_2030260
  path: multicoil_train/file_brain_AXT2_203_2030260.h5
  predefined_mask: null
  slice: 1
- filename: file_brain_AXT2_203_2030260
  path: multicoil_train/file_brain_AXT2_203_2030260.h5
  predefined_mask: null
  slice: 2
- filename: file_brain_AXT2_203_2030260
  path: multicoil_train/file_brain_AXT2_203_2030260.h5
  predefined_mask: null
  slice: 3
- filename: file_brain_AXT2_203_2030260
  path: multicoil_train/file_brain_AXT2_203_2030260.h5
  predefined_mask: null
  slice: 4
- filename: file_brain_AXT2_203_2030260
  path: multicoil_train/file_brain_AXT2_203_2030260.h5
  predefined_mask: null
  slice: 5
- filename: file_brain_AXT2_203_2030260
  path: multicoil_train/file_brain_AXT2_203_2030260.h5
  predefined_mask: null
  slice: 6
- filename: file_brain_AXT2_203_2030260
  path: multicoil_train/file_brain_AXT2_203_2030260.h5
  predefined_mask: null
  slice: 7
- filename: file_brain_AXT2_203_2030260
  path: multicoil_train/file_brain_AXT2_203_2030260.h5
  predefined_mask: null
  slice: 8
- filename: file_brain_AXT2_203_2030260
  path: multicoil_train/file_brain_AXT2_203_2030260.h5
  predefined_mask: null
  slice: 9
- filename: file_brain_AXT2_203_2030260
  path: multicoil_train/file_brain_AXT2_203_2030260.h5
  predefined_mask: null
  slice: 10
- filename: file_brain_AXT2_203_2030260
  path: multicoil_train/file_brain_AXT2_203_2030260.h5
  predefined_mask: null
  slice: 11
- filename: file_brain_AXT2_203_2030260
  path: multicoil_train/file_brain_AXT2_203_2030260.h5
  predefined_mask: null
  slice: 12
- filename: file_brain_AXT2_203_2030260
  path: multicoil_train/file_brain_AXT2_203_2030260.h5
  predefined_mask: null
  slice: 13
- filename: file_brain_AXT2_203_2030260
  path: multicoil_train/file_brain_AXT2_203_2030260.h5
  predefined_mask: null
  slice: 14
- filename: file_brain_AXT2_203_2030260
  path: multicoil_train/file_brain_AXT2_203_2030260.h5
  predefined_mask: null
  slice: 15
- filename: file_brain_AXT2_200_2000520
  path: multicoil_train/file_brain_AXT2_200_2000520.h5
  predefined_mask: null
  slice: 0
- filename: file_brain_AXT2_200_2000520
  path: multicoil_train/file_brain_AXT2_200_2000520.h5
  predefined_mask: null
  slice: 1
- filename: file_brain_AXT2_200_2000520
  path: multicoil_train/file_brain_AXT2_200_2000520.h5
  predefined_mask: null
  slice: 2
- filename: file_brain_AXT2_200_2000520
  path: multicoil_train/file_brain_AXT2_200_2000520.h5
  predefined_mask: null
  slice: 3
- filename: file_brain_AXT2_200_2000520
  path: multicoil_train/file_brain_AXT2_200_2000520.h5
  predefined_mask: null
  slice: 4
- filename: file_brain_AXT2_200_2000520
  path: multicoil_train/file_brain_AXT2_200_2000520.h5
  predefined_mask: null
  slice: 5
- filename: file_brain_AXT2_200_2000520
  path: multicoil_train/file_brain_AXT2_200_2000520.h5
  predefined_mask: null
  slice: 6
- filename: file_brain_AXT2_200_2000520
  path: multicoil_train/file_brain_AXT2_200_2000520.h5
  predefined_mask: null
  slice: 7
- filename: file_brain_AXT2_200_2000520
  path: multicoil_train/file_brain_AXT2_200_2000520.h5
  predefined_mask: null
  slice: 8
- filename: file_brain_AXT2_200_2000520
  path: multicoil_train/file_brain_AXT2_200_2000520.h5
  predefined_mask: null
  slice: 9
- filename: file_brain_AXT2_200_2000520
  path: multicoil_train/file_brain_AXT2_200_2000520.h5
  predefined_mask: null
  slice: 10
- filename: file_brain_AXT2_200_2000520
  path: multicoil_train/file_brain_AXT2_200_2000520.h5
  predefined_mask: null
  slice: 11
- filename: file_brain_AXT2_200_2000520
  path: multicoil_train/file_brain_AXT2_200_2000520.h5
  predefined_mask: null
  slice: 12
- filename: file_brain_AXT2_200_2000520
  path: multicoil_train/file_brain_AXT2_200_2000520.h5
  predefined_mask: null
  slice: 13
- filename: file_brain_AXT2_200_2000520
  path: multicoil_train/file_brain_AXT2_200_2000520.h5
  predefined_mask: null
  slice: 14
- filename: file_brain_AXT2_200_2000520
  path: multicoil_train/file_brain_AXT2_200_2000520.h5
  predefined_mask: null
  slice: 15
- filename: file_brain_AXT2_207_2070789
  path: multicoil_val/file_brain_AXT2_207_2070789.h5
  predefined_mask: null
  slice: 0
- filename: file_brain_AXT2_207_2070789
  path: multicoil_val/file_brain_AXT2_207_2070789.h5
  predefined_mask: null
  slice: 1
- filename: file_brain_AXT2_207_2070789
  path: multicoil_val/file_brain_AXT2_207_2070789.h5
  predefined_mask: null
  slice: 2
- filename: file_brain_AXT2_207_2070789
  path: multicoil_val/file_brain_AXT2_207_2070789.h5
  predefined_mask: null
  slice: 3
- filename: file_brain_AXT2_207_2070789
  path: multicoil_val/file_brain_AXT2_207_2070789.h5
  predefined_mask: null
  slice: 4
- filename: file_brain_AXT2_207_2070789
  path: multicoil_val/file_brain_AXT2_207_2070789.h5
  predefined_mask: null
  slice: 5
- filename: file_brain_AXT2_207_2070789
  path: multicoil_val/file_brain_AXT2_207_2070789.h5
  predefined_mask: null
  slice: 6
- filename: file_brain_AXT2_207_2070789
  path: multicoil_val/file_brain_AXT2_207_2070789.h5
  predefined_mask: null
  slice: 7
- filename: file_brain_AXT2_207_2070789
  path: multicoil_val/file_brain_AXT2_207_2070789.h5
  predefined_mask: null
  slice: 8
- filename: file_brain_AXT2_207_2070789
  path: multicoil_val/file_brain_AXT2_207_2070789.h5
  predefined_mask: null
  slice: 9
- filename: file_brain_AXT2_207_2070789
  path: multicoil_val/file_brain_AXT2_207_2070789.h5
  predefined_mask: null
  slice: 10
- filename: file_brain_AXT2_207_2070789
  path: multicoil_val/file_brain_AXT2_207_2070789.h5
  predefined_mask: null
  slice: 11
- filename: file_brain_AXT2_207_2070789
  path: multicoil_val/file_brain_AXT2_207_2070789.h5
  predefined_mask: null
  slice: 12
- filename: file_brain_AXT2_207_2070789
  path: multicoil_val/file_brain_AXT2_207_2070789.h5
  predefined_mask: null
  slice: 13
- filename: file_brain_AXT2_207_2070789
  path: multicoil_val/file_brain_AXT2_207_2070789.h5
  predefined_mask: null
  slice: 14
- filename: file_brain_AXT2_207_2070789
  path: multicoil_val/file_brain_AXT2_207_2070789.h5
  predefined_mask: null
  slice: 15
- filename: file_brain_AXT2_207_2070434
  path: multicoil_val/file_brain_AXT2_207_2070434.h5
  predefined_mask: null
  slice: 0
- filename: file_brain_AXT2_207_2070434
  path: multicoil_val/file_brain_AXT2_207_2070434.h5
  predefined_mask: null
  slice: 1
- filename: file_brain_AXT2_207_2070434
  path: multicoil_val/file_brain_AXT2_207_2070434.h5
  predefined_mask: null
  slice: 2
- filename: file_brain_AXT2_207_2070434
  path: multicoil_val/file_brain_AXT2_207_2070434.h5
  predefined_mask: null
  slice: 3
- filename: file_brain_AXT2_207_2070434
  path: multicoil_val/file_brain_AXT2_207_2070434.h5
  predefined_mask: null
  slice: 4
- filename: file_brain_AXT2_207_2070434
  path: multicoil_val/file_brain_AXT2_207_2070434.h5
  predefined_mask: null
  slice: 5
- filename: file_brain_AXT2_207_2070434
  path: multicoil_val/file_brain_AXT2_207_2070434.h5
  predefined_mask: null
  slice: 6
- filename: file_brain_AXT2_207_2070434
  path: multicoil_val/file_brain_AXT2_207_2070434.h5
  predefined_mask: null
  slice: 7
- filename: file_brain_AXT2_207_2070434
  path: multicoil_val/file_brain_AXT2_207_2070434.h5
  predefined_mask: null
  slice: 8
- filename: file_brain_AXT2_207_2070434
  path: multicoil_val/file_brain_AXT2_207_2070434.h5
  predefined_mask: null
  slice: 9
- filename: file_brain_AXT2_207_2070434
  path: multicoil_val/file_brain_AXT2_207_2070434.h5
  predefined_mask: null
  slice: 10
- filename: file_brain_AXT2_207_2070434
  path: multicoil_val/file_brain_AXT2_207_2070434.h5
  predefined_mask: null
  slice: 11
- filename: file_brain_AXT2_207_2070434
  path: multicoil_val/file_brain_AXT2_207_2070434.h5
  predefined_mask: null
  slice: 12
- filename: file_brain_AXT2_207_2070434
  path: multicoil_val/file_brain_AXT2_207_2070434.h5
  predefined_mask: null
  slice: 13
- filename: file_brain_AXT2_207_2070434
  path: multicoil_val/file_brain_AXT2_207_2070434.h5
  predefined_mask: null
  slice: 14
- filename: file_brain_AXT2_207_2070434
  path: multicoil_val/file_brain_AXT2_207_2070434.h5
  predefined_mask: null
  slice: 15
- filename: file_brain_AXT2_207_2070422
  path: multicoil_train/file_brain_AXT2_207_2070422.h5
  predefined_mask: null
  slice: 0
- filename: file_brain_AXT2_207_2070422
  path: multicoil_train/file_brain_AXT2_207_2070422.h5
  predefined_mask: null
  slice: 1
- filename: file_brain_AXT2_207_2070422
  path: multicoil_train/file_brain_AXT2_207_2070422.h5
  predefined_mask: null
  slice: 2
- filename: file_brain_AXT2_207_2070422
  path: multicoil_train/file_brain_AXT2_207_2070422.h5
  predefined_mask: null
  slice: 3
- filename: file_brain_AXT2_207_2070422
  path: multicoil_train/file_brain_AXT2_207_2070422.h5
  predefined_mask: null
  slice: 4
- filename: file_brain_AXT2_207_2070422
  path: multicoil_train/file_brain_AXT2_207_2070422.h5
  predefined_mask: null
  slice: 5
- filename: file_brain_AXT2_207_2070422
  path: multicoil_train/file_brain_AXT2_207_2070422.h5
  predefined_mask: null
  slice: 6
- filename: file_brain_AXT2_207_2070422
  path: multicoil_train/file_brain_AXT2_207_2070422.h5
  predefined_mask: null
  slice: 7
- filename: file_brain_AXT2_207_2070422
  path: multicoil_train/file_brain_AXT2_207_2070422.h5
  predefined_mask: null
  slice: 8
- filename: file_brain_AXT2_207_2070422
  path: multicoil_train/file_brain_AXT2_207_2070422.h5
  predefined_mask: null
  slice: 9
- filename: file_brain_AXT2_207_2070422
  path: multicoil_train/file_brain_AXT2_207_2070422.h5
  predefined_mask: null
  slice: 10
- filename: file_brain_AXT2_207_2070422
  path: multicoil_train/file_brain_AXT2_207_2070422.h5
  predefined_mask: null
  slice: 11
- filename: file_brain_AXT2_207_2070422
  path: multicoil_train/file_brain_AXT2_207_2070422.h5
  predefined_mask: null
  slice: 12
- filename: file_brain_AXT2_207_2070422
  path: multicoil_train/file_brain_AXT2_207_2070422.h5
  predefined_mask: null
  slice: 13
- filename: file_brain_AXT2_207_2070422
  path: multicoil_train/file_brain_AXT2_207_2070422.h5
  predefined_mask: null
  slice: 14
- filename: file_brain_AXT2_207_2070422
  path: multicoil_train/file_brain_AXT2_207_2070422.h5
  predefined_mask: null
  slice: 15
- filename: file_brain_AXT2_207_2070761
  path: multicoil_train/file_brain_AXT2_207_2070761.h5
  predefined_mask: null
  slice: 0
- filename: file_brain_AXT2_207_2070761
  path: multicoil_train/file_brain_AXT2_207_2070761.h5
  predefined_mask: null
  slice: 1
- filename: file_brain_AXT2_207_2070761
  path: multicoil_train/file_brain_AXT2_207_2070761.h5
  predefined_mask: null
  slice: 2
- filename: file_brain_AXT2_207_2070761
  path: multicoil_train/file_brain_AXT2_207_2070761.h5
  predefined_mask: null
  slice: 3
