- filename: file_brain_AXT2_210_6001650
  path: multicoil_val/file_brain_AXT2_210_6001650.h5
  predefined_mask: null
  slice: 0
- filename: file_brain_AXT2_210_6001650
  path: multicoil_val/file_brain_AXT2_210_6001650.h5
  predefined_mask: null
  slice: 1
- filename: file_brain_AXT2_210_6001650
  path: multicoil_val/file_brain_AXT2_210_6001650.h5
  predefined_mask: null
  slice: 2
- filename: file_brain_AXT2_210_6001650
  path: multicoil_val/file_brain_AXT2_210_6001650.h5
  predefined_mask: null
  slice: 3
- filename: file_brain_AXT2_210_6001650
  path: multicoil_val/file_brain_AXT2_210_6001650.h5
  predefined_mask: null
  slice: 4
- filename: file_brain_AXT2_210_6001650
  path: multicoil_val/file_brain_AXT2_210_6001650.h5
  predefined_mask: null
  slice: 5
- filename: file_brain_AXT2_210_6001650
  path: multicoil_val/file_brain_AXT2_210_6001650.h5
  predefined_mask: null
  slice: 6
- filename: file_brain_AXT2_210_6001650
  path: multicoil_val/file_brain_AXT2_210_6001650.h5
  predefined_mask: null
  slice: 7
- filename: file_brain_AXT2_210_6001650
  path: multicoil_val/file_brain_AXT2_210_6001650.h5
  predefined_mask: null
  slice: 8
- filename: file_brain_AXT2_210_6001650
  path: multicoil_val/file_brain_AXT2_210_6001650.h5
  predefined_mask: null
  slice: 9
- filename: file_brain_AXT2_210_6001650
  path: multicoil_val/file_brain_AXT2_210_6001650.h5
  predefined_mask: null
  slice: 10
- filename: file_brain_AXT2_210_6001650
  path: multicoil_val/file_brain_AXT2_210_6001650.h5
  predefined_mask: null
  slice: 11
- filename: file_brain_AXT2_210_6001650
  path: multicoil_val/file_brain_AXT2_210_6001650.h5
  predefined_mask: null
  slice: 12
- filename: file_brain_AXT2_210_6001650
  path: multicoil_val/file_brain_AXT2_210_6001650.h5
  predefined_mask: null
  slice: 13
- filename: file_brain_AXT2_208_2080551
  path: multicoil_train/file_brain_AXT2_208_2080551.h5
  predefined_mask: null
  slice: 0
- filename: file_brain_AXT2_208_2080551
  path: multicoil_train/file_brain_AXT2_208_2080551.h5
  predefined_mask: null
  slice: 1
- filename: file_brain_AXT2_208_2080551
  path: multicoil_train/file_brain_AXT2_208_2080551.h5
  predefined_mask: null
  slice: 2
- filename: file_brain_AXT2_208_2080551
  path: multicoil_train/file_brain_AXT2_208_2080551.h5
  predefined_mask: null
  slice: 3
- filename: file_brain_AXT2_208_2080551
  path: multicoil_train/file_brain_AXT2_208_2080551.h5
  predefined_mask: null
  slice: 4
- filename: file_brain_AXT2_208_2080551
  path: multicoil_train/file_brain_AXT2_208_2080551.h5
  predefined_mask: null
  slice: 5
- filename: file_brain_AXT2_208_2080551
  path: multicoil_train/file_brain_AXT2_208_2080551.h5
  predefined_mask: null
  slice: 6
- filename: file_brain_AXT2_208_2080551
  path: multicoil_train/file_brain_AXT2_208_2080551.h5
  predefined_mask: null
  slice: 7
- filename: file_brain_AXT2_208_2080551
  path: multicoil_train/file_brain_AXT2_208_2080551.h5
  predefined_mask: null
  slice: 8
- filename: file_brain_AXT2_208_2080551
  path: multicoil_train/file_brain_AXT2_208_2080551.h5
  predefined_mask: null
  slice: 9
- filename: file_brain_AXT2_208_2080551
  path: multicoil_train/file_brain_AXT2_208_2080551.h5
  predefined_mask: null
  slice: 10
- filename: file_brain_AXT2_208_2080551
  path: multicoil_train/file_brain_AXT2_208_2080551.h5
  predefined_mask: null
  slice: 11
- filename: file_brain_AXT2_208_2080551
  path: multicoil_train/file_brain_AXT2_208_2080551.h5
  predefined_mask: null
  slice: 12
- filename: file_brain_AXT2_208_2080551
  path: multicoil_train/file_brain_AXT2_208_2080551.h5
  predefined_mask: null
  slice: 13
- filename: file_brain_AXT2_208_2080551
  path: multicoil_train/file_brain_AXT2_208_2080551.h5
  predefined_mask: null
  slice: 14
- filename: file_brain_AXT2_208_2080551
  path: multicoil_train/file_brain_AXT2_208_2080551.h5
  predefined_mask: null
  slice: 15
- filename: file_brain_AXT2_207_2070211
  path: multicoil_train/file_brain_AXT2_207_2070211.h5
  predefined_mask: null
  slice: 0
- filename: file_brain_AXT2_207_2070211
  path: multicoil_train/file_brain_AXT2_207_2070211.h5
  predefined_mask: null
  slice: 1
- filename: file_brain_AXT2_207_2070211
  path: multicoil_train/file_brain_AXT2_207_2070211.h5
  predefined_mask: null
  slice: 2
- filename: file_brain_AXT2_207_2070211
  path: multicoil_train/file_brain_AXT2_207_2070211.h5
  predefined_mask: null
  slice: 3
- filename: file_brain_AXT2_207_2070211
  path: multicoil_train/file_brain_AXT2_207_2070211.h5
  predefined_mask: null
  slice: 4
- filename: file_brain_AXT2_207_2070211
  path: multicoil_train/file_brain_AXT2_207_2070211.h5
  predefined_mask: null
  slice: 5
- filename: file_brain_AXT2_207_2070211
  path: multicoil_train/file_brain_AXT2_207_2070211.h5
  predefined_mask: null
  slice: 6
- filename: file_brain_AXT2_207_2070211
  path: multicoil_train/file_brain_AXT2_207_2070211.h5
  predefined_mask: null
  slice: 7
- filename: file_brain_AXT2_207_2070211
  path: multicoil_train/file_brain_AXT2_207_2070211.h5
  predefined_mask: null
  slice: 8
- filename: file_brain_AXT2_207_2070211
  path: multicoil_train/file_brain_AXT2_207_2070211.h5
  predefined_mask: null
  slice: 9
- filename: file_brain_AXT2_207_2070211
  path: multicoil_train/file_brain_AXT2_207_2070211.h5
  predefined_mask: null
  slice: 10
- filename: file_brain_AXT2_207_2070211
  path: multicoil_train/file_brain_AXT2_207_2070211.h5
  predefined_mask: null
  slice: 11
- filename: file_brain_AXT2_205_2050188
  path: multicoil_val/file_brain_AXT2_205_2050188.h5
  predefined_mask: null
  slice: 0
- filename: file_brain_AXT2_205_2050188
  path: multicoil_val/file_brain_AXT2_205_2050188.h5
  predefined_mask: null
  slice: 1
- filename: file_brain_AXT2_205_2050188
  path: multicoil_val/file_brain_AXT2_205_2050188.h5
  predefined_mask: null
  slice: 2
- filename: file_brain_AXT2_205_2050188
  path: multicoil_val/file_brain_AXT2_205_2050188.h5
  predefined_mask: null
  slice: 3
- filename: file_brain_AXT2_205_2050188
  path: multicoil_val/file_brain_AXT2_205_2050188.h5
  predefined_mask: null
  slice: 4
- filename: file_brain_AXT2_205_2050188
  path: multicoil_val/file_brain_AXT2_205_2050188.h5
  predefined_mask: null
  slice: 5
- filename: file_brain_AXT2_205_2050188
  path: multicoil_val/file_brain_AXT2_205_2050188.h5
  predefined_mask: null
  slice: 6
- filename: file_brain_AXT2_205_2050188
  path: multicoil_val/file_brain_AXT2_205_2050188.h5
  predefined_mask: null
  slice: 7
