- filename: file_brain_AXT2_205_6000140
  path: multicoil_train/file_brain_AXT2_205_6000140.h5
  predefined_mask: null
  slice: 0
- filename: file_brain_AXT2_205_6000140
  path: multicoil_train/file_brain_AXT2_205_6000140.h5
  predefined_mask: null
  slice: 1
- filename: file_brain_AXT2_205_6000140
  path: multicoil_train/file_brain_AXT2_205_6000140.h5
  predefined_mask: null
  slice: 2
- filename: file_brain_AXT2_205_6000140
  path: multicoil_train/file_brain_AXT2_205_6000140.h5
  predefined_mask: null
  slice: 3
- filename: file_brain_AXT2_205_6000140
  path: multicoil_train/file_brain_AXT2_205_6000140.h5
  predefined_mask: null
  slice: 4
- filename: file_brain_AXT2_205_6000140
  path: multicoil_train/file_brain_AXT2_205_6000140.h5
  predefined_mask: null
  slice: 5
- filename: file_brain_AXT2_208_2080064
  path: multicoil_train/file_brain_AXT2_208_2080064.h5
  predefined_mask: null
  slice: 0
- filename: file_brain_AXT2_208_2080064
  path: multicoil_train/file_brain_AXT2_208_2080064.h5
  predefined_mask: null
  slice: 1
- filename: file_brain_AXT2_208_2080064
  path: multicoil_train/file_brain_AXT2_208_2080064.h5
  predefined_mask: null
  slice: 2
- filename: file_brain_AXT2_208_2080064
  path: multicoil_train/file_brain_AXT2_208_2080064.h5
  predefined_mask: null
  slice: 3
- filename: file_brain_AXT2_208_2080064
  path: multicoil_train/file_brain_AXT2_208_2080064.h5
  predefined_mask: null
  slice: 4
- filename: file_brain_AXT2_208_2080064
  path: multicoil_train/file_brain_AXT2_208_2080064.h5
  predefined_mask: null
  slice: 5
- filename: file_brain_AXT2_208_2080064
  path: multicoil_train/file_brain_AXT2_208_2080064.h5
  predefined_mask: null
  slice: 6
- filename: file_brain_AXT2_208_2080064
  path: multicoil_train/file_brain_AXT2_208_2080064.h5
  predefined_mask: null
  slice: 7
- filename: file_brain_AXT2_208_2080064
  path: multicoil_train/file_brain_AXT2_208_2080064.h5
  predefined_mask: null
  slice: 8
- filename: file_brain_AXT2_208_2080064
  path: multicoil_train/file_brain_AXT2_208_2080064.h5
  predefined_mask: null
  slice: 9
- filename: file_brain_AXT2_208_2080064
  path: multicoil_train/file_brain_AXT2_208_2080064.h5
  predefined_mask: null
  slice: 10
- filename: file_brain_AXT2_208_2080064
  path: multicoil_train/file_brain_AXT2_208_2080064.h5
  predefined_mask: null
  slice: 11
- filename: file_brain_AXT2_208_2080064
  path: multicoil_train/file_brain_AXT2_208_2080064.h5
  predefined_mask: null
  slice: 12
- filename: file_brain_AXT2_208_2080064
  path: multicoil_train/file_brain_AXT2_208_2080064.h5
  predefined_mask: null
  slice: 13
- filename: file_brain_AXT2_208_2080064
  path: multicoil_train/file_brain_AXT2_208_2080064.h5
  predefined_mask: null
  slice: 14
- filename: file_brain_AXT2_208_2080064
  path: multicoil_train/file_brain_AXT2_208_2080064.h5
  predefined_mask: null
  slice: 15
- filename: file_brain_AXT2_201_2010161
  path: multicoil_train/file_brain_AXT2_201_2010161.h5
  predefined_mask: null
  slice: 0
- filename: file_brain_AXT2_201_2010161
  path: multicoil_train/file_brain_AXT2_201_2010161.h5
  predefined_mask: null
  slice: 1
- filename: file_brain_AXT2_201_2010161
  path: multicoil_train/file_brain_AXT2_201_2010161.h5
  predefined_mask: null
  slice: 2
- filename: file_brain_AXT2_201_2010161
  path: multicoil_train/file_brain_AXT2_201_2010161.h5
  predefined_mask: null
  slice: 3
- filename: file_brain_AXT2_201_2010161
  path: multicoil_train/file_brain_AXT2_201_2010161.h5
  predefined_mask: null
  slice: 4
- filename: file_brain_AXT2_201_2010161
  path: multicoil_train/file_brain_AXT2_201_2010161.h5
  predefined_mask: null
  slice: 5
- filename: file_brain_AXT2_201_2010161
  path: multicoil_train/file_brain_AXT2_201_2010161.h5
  predefined_mask: null
  slice: 6
- filename: file_brain_AXT2_201_2010161
  path: multicoil_train/file_brain_AXT2_201_2010161.h5
  predefined_mask: null
  slice: 7
- filename: file_brain_AXT2_201_2010161
  path: multicoil_train/file_brain_AXT2_201_2010161.h5
  predefined_mask: null
  slice: 8
- filename: file_brain_AXT2_201_2010161
  path: multicoil_train/file_brain_AXT2_201_2010161.h5
  predefined_mask: null
  slice: 9
- filename: file_brain_AXT2_201_2010161
  path: multicoil_train/file_brain_AXT2_201_2010161.h5
  predefined_mask: null
  slice: 10
- filename: file_brain_AXT2_201_2010161
  path: multicoil_train/file_brain_AXT2_201_2010161.h5
  predefined_mask: null
  slice: 11
- filename: file_brain_AXT2_201_2010161
  path: multicoil_train/file_brain_AXT2_201_2010161.h5
  predefined_mask: null
  slice: 12
- filename: file_brain_AXT2_201_2010161
  path: multicoil_train/file_brain_AXT2_201_2010161.h5
  predefined_mask: null
  slice: 13
- filename: file_brain_AXT2_201_2010161
  path: multicoil_train/file_brain_AXT2_201_2010161.h5
  predefined_mask: null
  slice: 14
- filename: file_brain_AXT2_201_2010161
  path: multicoil_train/file_brain_AXT2_201_2010161.h5
  predefined_mask: null
  slice: 15
- filename: file_brain_AXT2_210_2100169
  path: multicoil_train/file_brain_AXT2_210_2100169.h5
  predefined_mask: null
  slice: 0
- filename: file_brain_AXT2_210_2100169
  path: multicoil_train/file_brain_AXT2_210_2100169.h5
  predefined_mask: null
  slice: 1
- filename: file_brain_AXT2_210_2100169
  path: multicoil_train/file_brain_AXT2_210_2100169.h5
  predefined_mask: null
  slice: 2
- filename: file_brain_AXT2_210_2100169
  path: multicoil_train/file_brain_AXT2_210_2100169.h5
  predefined_mask: null
  slice: 3
- filename: file_brain_AXT2_210_2100169
  path: multicoil_train/file_brain_AXT2_210_2100169.h5
  predefined_mask: null
  slice: 4
- filename: file_brain_AXT2_210_2100169
  path: multicoil_train/file_brain_AXT2_210_2100169.h5
  predefined_mask: null
  slice: 5
- filename: file_brain_AXT2_210_2100169
  path: multicoil_train/file_brain_AXT2_210_2100169.h5
  predefined_mask: null
  slice: 6
- filename: file_brain_AXT2_210_2100169
  path: multicoil_train/file_brain_AXT2_210_2100169.h5
  predefined_mask: null
  slice: 7
- filename: file_brain_AXT2_210_2100169
  path: multicoil_train/file_brain_AXT2_210_2100169.h5
  predefined_mask: null
  slice: 8
- filename: file_brain_AXT2_210_2100169
  path: multicoil_train/file_brain_AXT2_210_2100169.h5
  predefined_mask: null
  slice: 9
- filename: file_brain_AXT2_210_2100169
  path: multicoil_train/file_brain_AXT2_210_2100169.h5
  predefined_mask: null
  slice: 10
- filename: file_brain_AXT2_210_2100169
  path: multicoil_train/file_brain_AXT2_210_2100169.h5
  predefined_mask: null
  slice: 11
- filename: file_brain_AXT2_210_2100169
  path: multicoil_train/file_brain_AXT2_210_2100169.h5
  predefined_mask: null
  slice: 12
- filename: file_brain_AXT2_210_2100169
  path: multicoil_train/file_brain_AXT2_210_2100169.h5
  predefined_mask: null
  slice: 13
- filename: file_brain_AXT2_210_2100169
  path: multicoil_train/file_brain_AXT2_210_2100169.h5
  predefined_mask: null
  slice: 14
- filename: file_brain_AXT2_210_2100169
  path: multicoil_train/file_brain_AXT2_210_2100169.h5
  predefined_mask: null
  slice: 15
- filename: file_brain_AXT2_210_6001757
  path: multicoil_train/file_brain_AXT2_210_6001757.h5
  predefined_mask: null
  slice: 0
- filename: file_brain_AXT2_210_6001757
  path: multicoil_train/file_brain_AXT2_210_6001757.h5
  predefined_mask: null
  slice: 1
- filename: file_brain_AXT2_210_6001757
  path: multicoil_train/file_brain_AXT2_210_6001757.h5
  predefined_mask: null
  slice: 2
- filename: file_brain_AXT2_210_6001757
  path: multicoil_train/file_brain_AXT2_210_6001757.h5
  predefined_mask: null
  slice: 3
- filename: file_brain_AXT2_210_6001757
  path: multicoil_train/file_brain_AXT2_210_6001757.h5
  predefined_mask: null
  slice: 4
- filename: file_brain_AXT2_210_6001757
  path: multicoil_train/file_brain_AXT2_210_6001757.h5
  predefined_mask: null
  slice: 5
- filename: file_brain_AXT2_210_6001757
  path: multicoil_train/file_brain_AXT2_210_6001757.h5
  predefined_mask: null
  slice: 6
- filename: file_brain_AXT2_210_6001757
  path: multicoil_train/file_brain_AXT2_210_6001757.h5
  predefined_mask: null
  slice: 7
- filename: file_brain_AXT2_210_6001757
  path: multicoil_train/file_brain_AXT2_210_6001757.h5
  predefined_mask: null
  slice: 8
- filename: file_brain_AXT2_210_6001757
  path: multicoil_train/file_brain_AXT2_210_6001757.h5
  predefined_mask: null
  slice: 9
- filename: file_brain_AXT2_210_6001757
  path: multicoil_train/file_brain_AXT2_210_6001757.h5
  predefined_mask: null
  slice: 10
- filename: file_brain_AXT2_210_6001757
  path: multicoil_train/file_brain_AXT2_210_6001757.h5
  predefined_mask: null
  slice: 11
- filename: file_brain_AXT2_210_6001757
  path: multicoil_train/file_brain_AXT2_210_6001757.h5
  predefined_mask: null
  slice: 12
- filename: file_brain_AXT2_210_6001757
  path: multicoil_train/file_brain_AXT2_210_6001757.h5
  predefined_mask: null
  slice: 13
- filename: file_brain_AXT2_210_6001757
  path: multicoil_train/file_brain_AXT2_210_6001757.h5
  predefined_mask: null
  slice: 14
- filename: file_brain_AXT2_210_6001757
  path: multicoil_train/file_brain_AXT2_210_6001757.h5
  predefined_mask: null
  slice: 15
- filename: file_brain_AXT2_207_2070080
  path: multicoil_train/file_brain_AXT2_207_2070080.h5
  predefined_mask: null
  slice: 0
- filename: file_brain_AXT2_207_2070080
  path: multicoil_train/file_brain_AXT2_207_2070080.h5
  predefined_mask: null
  slice: 1
- filename: file_brain_AXT2_207_2070080
  path: multicoil_train/file_brain_AXT2_207_2070080.h5
  predefined_mask: null
  slice: 2
- filename: file_brain_AXT2_207_2070080
  path: multicoil_train/file_brain_AXT2_207_2070080.h5
  predefined_mask: null
  slice: 3
- filename: file_brain_AXT2_207_2070080
  path: multicoil_train/file_brain_AXT2_207_2070080.h5
  predefined_mask: null
  slice: 4
- filename: file_brain_AXT2_207_2070080
  path: multicoil_train/file_brain_AXT2_207_2070080.h5
  predefined_mask: null
  slice: 5
- filename: file_brain_AXT2_207_2070080
  path: multicoil_train/file_brain_AXT2_207_2070080.h5
  predefined_mask: null
  slice: 6
- filename: file_brain_AXT2_207_2070080
  path: multicoil_train/file_brain_AXT2_207_2070080.h5
  predefined_mask: null
  slice: 7
- filename: file_brain_AXT2_207_2070080
  path: multicoil_train/file_brain_AXT2_207_2070080.h5
  predefined_mask: null
  slice: 8
- filename: file_brain_AXT2_207_2070080
  path: multicoil_train/file_brain_AXT2_207_2070080.h5
  predefined_mask: null
  slice: 9
- filename: file_brain_AXT2_207_2070080
  path: multicoil_train/file_brain_AXT2_207_2070080.h5
  predefined_mask: null
  slice: 10
- filename: file_brain_AXT2_207_2070080
  path: multicoil_train/file_brain_AXT2_207_2070080.h5
  predefined_mask: null
  slice: 11
- filename: file_brain_AXT2_207_2070080
  path: multicoil_train/file_brain_AXT2_207_2070080.h5
  predefined_mask: null
  slice: 12
- filename: file_brain_AXT2_207_2070080
  path: multicoil_train/file_brain_AXT2_207_2070080.h5
  predefined_mask: null
  slice: 13
- filename: file_brain_AXT2_207_2070080
  path: multicoil_train/file_brain_AXT2_207_2070080.h5
  predefined_mask: null
  slice: 14
- filename: file_brain_AXT2_207_2070080
  path: multicoil_train/file_brain_AXT2_207_2070080.h5
  predefined_mask: null
  slice: 15
- filename: file_brain_AXT2_200_6002515
  path: multicoil_train/file_brain_AXT2_200_6002515.h5
  predefined_mask: null
  slice: 0
- filename: file_brain_AXT2_200_6002515
  path: multicoil_train/file_brain_AXT2_200_6002515.h5
  predefined_mask: null
  slice: 1
- filename: file_brain_AXT2_200_6002515
  path: multicoil_train/file_brain_AXT2_200_6002515.h5
  predefined_mask: null
  slice: 2
- filename: file_brain_AXT2_200_6002515
  path: multicoil_train/file_brain_AXT2_200_6002515.h5
  predefined_mask: null
  slice: 3
- filename: file_brain_AXT2_200_6002515
  path: multicoil_train/file_brain_AXT2_200_6002515.h5
  predefined_mask: null
  slice: 4
- filename: file_brain_AXT2_200_6002515
  path: multicoil_train/file_brain_AXT2_200_6002515.h5
  predefined_mask: null
  slice: 5
- filename: file_brain_AXT2_200_6002515
  path: multicoil_train/file_brain_AXT2_200_6002515.h5
  predefined_mask: null
  slice: 6
- filename: file_brain_AXT2_200_6002515
  path: multicoil_train/file_brain_AXT2_200_6002515.h5
  predefined_mask: null
  slice: 7
- filename: file_brain_AXT2_200_6002515
  path: multicoil_train/file_brain_AXT2_200_6002515.h5
  predefined_mask: null
  slice: 8
- filename: file_brain_AXT2_200_6002515
  path: multicoil_train/file_brain_AXT2_200_6002515.h5
  predefined_mask: null
  slice: 9
- filename: file_brain_AXT2_200_6002515
  path: multicoil_train/file_brain_AXT2_200_6002515.h5
  predefined_mask: null
  slice: 10
- filename: file_brain_AXT2_200_6002515
  path: multicoil_train/file_brain_AXT2_200_6002515.h5
  predefined_mask: null
  slice: 11
- filename: file_brain_AXT2_200_6002515
  path: multicoil_train/file_brain_AXT2_200_6002515.h5
  predefined_mask: null
  slice: 12
- filename: file_brain_AXT2_200_6002515
  path: multicoil_train/file_brain_AXT2_200_6002515.h5
  predefined_mask: null
  slice: 13
