- filename: file_brain_AXT2_209_6001017
  path: multicoil_train/file_brain_AXT2_209_6001017.h5
  slice: null
- filename: file_brain_AXT2_200_6002479
  path: multicoil_train/file_brain_AXT2_200_6002479.h5
  slice: null
- filename: file_brain_AXT2_207_2070021
  path: multicoil_val/file_brain_AXT2_207_2070021.h5
  slice: null
- filename: file_brain_AXT2_207_2070003
  path: multicoil_train/file_brain_AXT2_207_2070003.h5
  slice: null
- filename: file_brain_AXT2_207_2070200
  path: multicoil_val/file_brain_AXT2_207_2070200.h5
  slice: null
- filename: file_brain_AXT2_208_2080575
  path: multicoil_val/file_brain_AXT2_208_2080575.h5
  slice: null
- filename: file_brain_AXT2_203_2030161
  path: multicoil_train/file_brain_AXT2_203_2030161.h5
  slice: null
- filename: file_brain_AXT2_207_2070781
  path: multicoil_train/file_brain_AXT2_207_2070781.h5
  slice: null
- filename: file_brain_AXT2_207_2070800
  path: multicoil_train/file_brain_AXT2_207_2070800.h5
  slice: null
- filename: file_brain_AXT2_207_2070739
  path: multicoil_train/file_brain_AXT2_207_2070739.h5
  slice: null
- filename: file_brain_AXT2_203_2030090
  path: multicoil_train/file_brain_AXT2_203_2030090.h5
  slice: null
- filename: file_brain_AXT2_207_2070052
  path: multicoil_train/file_brain_AXT2_207_2070052.h5
  slice: null
- filename: file_brain_AXT2_208_2080426
  path: multicoil_train/file_brain_AXT2_208_2080426.h5
  slice: null
- filename: file_brain_AXT2_208_2080408
  path: multicoil_train/file_brain_AXT2_208_2080408.h5
  slice: null
- filename: file_brain_AXT2_207_2070586
  path: multicoil_train/file_brain_AXT2_207_2070586.h5
  slice: null
- filename: file_brain_AXT2_208_2080485
  path: multicoil_train/file_brain_AXT2_208_2080485.h5
  slice: null
- filename: file_brain_AXT2_208_2080295
  path: multicoil_train/file_brain_AXT2_208_2080295.h5
  slice: null
- filename: file_brain_AXT2_208_2080659
  path: multicoil_train/file_brain_AXT2_208_2080659.h5
  slice: null
- filename: file_brain_AXT2_209_2090236
  path: multicoil_train/file_brain_AXT2_209_2090236.h5
  slice: null
- filename: file_brain_AXT2_202_2020512
  path: multicoil_train/file_brain_AXT2_202_2020512.h5
  slice: null
- filename: file_brain_AXT2_210_6001651
  path: multicoil_train/file_brain_AXT2_210_6001651.h5
  slice: null
- filename: file_brain_AXT2_201_2010095
  path: multicoil_train/file_brain_AXT2_201_2010095.h5
  slice: null
- filename: file_brain_AXT2_201_2010302
  path: multicoil_train/file_brain_AXT2_201_2010302.h5
  slice: null
- filename: file_brain_AXT2_210_2100244
  path: multicoil_train/file_brain_AXT2_210_2100244.h5
  slice: null
- filename: file_brain_AXT2_202_2020376
  path: multicoil_train/file_brain_AXT2_202_2020376.h5
  slice: null
- filename: file_brain_AXT2_200_6002005
  path: multicoil_train/file_brain_AXT2_200_6002005.h5
  slice: null
- filename: file_brain_AXT2_202_2020258
  path: multicoil_train/file_brain_AXT2_202_2020258.h5
  slice: null
- filename: file_brain_AXT2_209_2090237
  path: multicoil_val/file_brain_AXT2_209_2090237.h5
  slice: null
- filename: file_brain_AXT2_205_2050099
  path: multicoil_train/file_brain_AXT2_205_2050099.h5
  slice: null
- filename: file_brain_AXT2_209_6001400
  path: multicoil_train/file_brain_AXT2_209_6001400.h5
  slice: null
- filename: file_brain_AXT2_210_2100265
  path: multicoil_val/file_brain_AXT2_210_2100265.h5
  slice: null
- filename: file_brain_AXT2_200_2000550
  path: multicoil_train/file_brain_AXT2_200_2000550.h5
  slice: null
- filename: file_brain_AXT2_205_2050086
  path: multicoil_train/file_brain_AXT2_205_2050086.h5
  slice: null
- filename: file_brain_AXT2_210_2100340
  path: multicoil_train/file_brain_AXT2_210_2100340.h5
  slice: null
- filename: file_brain_AXT2_200_2000273
  path: multicoil_train/file_brain_AXT2_200_2000273.h5
  slice: null
- filename: file_brain_AXT2_209_2090214
  path: multicoil_train/file_brain_AXT2_209_2090214.h5
  slice: null
- filename: file_brain_AXT2_210_6001725
  path: multicoil_train/file_brain_AXT2_210_6001725.h5
  slice: null
- filename: file_brain_AXT2_200_2000317
  path: multicoil_train/file_brain_AXT2_200_2000317.h5
  slice: null
- filename: file_brain_AXT2_205_2050262
  path: multicoil_train/file_brain_AXT2_205_2050262.h5
  slice: null
- filename: file_brain_AXT2_210_2100054
  path: multicoil_val/file_brain_AXT2_210_2100054.h5
  slice: null
- filename: file_brain_AXT2_210_2100260
  path: multicoil_train/file_brain_AXT2_210_2100260.h5
  slice: null
- filename: file_brain_AXT2_200_2000044
  path: multicoil_train/file_brain_AXT2_200_2000044.h5
  slice: null
- filename: file_brain_AXT2_210_6001898
  path: multicoil_train/file_brain_AXT2_210_6001898.h5
  slice: null
- filename: file_brain_AXT2_209_6001150
  path: multicoil_train/file_brain_AXT2_209_6001150.h5
  slice: null
- filename: file_brain_AXT2_205_2050267
  path: multicoil_train/file_brain_AXT2_205_2050267.h5
  slice: null
- filename: file_brain_AXT2_210_2100105
  path: multicoil_train/file_brain_AXT2_210_2100105.h5
  slice: null
- filename: file_brain_AXT2_205_6000108
  path: multicoil_train/file_brain_AXT2_205_6000108.h5
  slice: null
- filename: file_brain_AXT2_201_2010589
  path: multicoil_train/file_brain_AXT2_201_2010589.h5
  slice: null
- filename: file_brain_AXT2_201_2010209
  path: multicoil_val/file_brain_AXT2_201_2010209.h5
  slice: null
- filename: file_brain_AXT2_200_6002610
  path: multicoil_train/file_brain_AXT2_200_6002610.h5
  slice: null
- filename: file_brain_AXT2_206_2060013
  path: multicoil_train/file_brain_AXT2_206_2060013.h5
  slice: null
- filename: file_brain_AXT2_200_2000298
  path: multicoil_train/file_brain_AXT2_200_2000298.h5
  slice: null
- filename: file_brain_AXT2_210_6001694
  path: multicoil_train/file_brain_AXT2_210_6001694.h5
  slice: null
- filename: file_brain_AXT2_210_2100188
  path: multicoil_train/file_brain_AXT2_210_2100188.h5
  slice: null
- filename: file_brain_AXT2_210_6001883
  path: multicoil_train/file_brain_AXT2_210_6001883.h5
  slice: null
- filename: file_brain_AXT2_200_2000590
  path: multicoil_val/file_brain_AXT2_200_2000590.h5
  slice: null
- filename: file_brain_AXT2_200_6002657
  path: multicoil_val/file_brain_AXT2_200_6002657.h5
  slice: null
- filename: file_brain_AXT2_201_2010067
  path: multicoil_train/file_brain_AXT2_201_2010067.h5
  slice: null
- filename: file_brain_AXT2_202_2020237
  path: multicoil_train/file_brain_AXT2_202_2020237.h5
  slice: null
- filename: file_brain_AXT2_206_6000253
  path: multicoil_train/file_brain_AXT2_206_6000253.h5
  slice: null
- filename: file_brain_AXT2_200_6002551
  path: multicoil_train/file_brain_AXT2_200_6002551.h5
  slice: null
